### PR TITLE
Adding support for .NET Core & custom instance methods

### PR DESCRIPTION
**Pull request by aviv86**
This moves the project to .NET Standard 1.3, so it can run on the CoreCLR.
I also added support for translating instance methods, so the following works:

```
// translates to: array.splice(2,1);
 Expression<Func<JSArray, object>> expr = array => array.RemoveAt(2);

public class JSArray
{
	[JavascriptMethodName("splice", PositionalArguments = new object[] {0,1})]
	public JSArray RemoveAt(int index)
	{
		throw new NotSupportedException("Never called");
	}
}

 
```

### CODE REVIEW

**Comment by masbicudo** [comment]
Hi! thanks for your contribution.

Is the `project.lock.json` file needed?
I read something about this file, and it seems that committing it is sometimes but not always needed.
http://stackoverflow.com/questions/38448468/should-project-lock-json-file-be-checked-into-source-control-asp-net-core-1-0

**Comment by masbicudo** [comment]
I like the idea of allowing annotations via attributes... I didn't have much time for this project lately, but I'd like to evolve that idea into something that allows declarative customization, that could use multiple sources such as attributes, some kind of fluent configuration code, and data files (e.g. json/xml).

I personally like the fluent configuration style, since it allows one to control the behavior of the translation for third-party classes, which code cannot be changed.

**Comment by masbicudo** [comment]
Hello again!

I have reviewed the code, and I see that you found an issue with the `GetMemberMetadataWithCache`.
Your implementation is the safest way indeed, but I'll add the `MemoryBarrier` again so that weaker memory models are supported.

My previous implementation assumed that the `ContainsKey` could never return true by mistake, on a constantly growing dictionary, even if writes happened in the middle of the operation. That assumption is of course implementation specific, and it could fail when running on other .net implementations.

I explain the rationale behind the `MemoryBarrier` when doing double checked locking in this StackOverflow answer: http://stackoverflow.com/a/12945510/195417
I don't know of an implementation of the CLR that has a weaker memory model, but if the specs allow it, we'd better be safe than sorry.

**Comment by masbicudo** [comment]
Merged!

**Comment by ayende** [comment]
@masbicudo Double checked locking is guaranteed to work on the CLR.
See: http://joeduffyblog.com/2006/01/26/broken-variants-on-doublechecked-locking/

The problem is that ContainsKey isn't thread safe with regards to modifications to the dictionary. The create new dictionary works around that because the instance is only ever written to on init, and after publication to the wide world, it is just read only.

**Comment by masbicudo** [comment]
@ayende Hi! That's for a specific implementation of the CLR. In [this post](http://joeduffyblog.com/2007/11/10/clr-20-memory-model/) Joe Duffy states that Mono, for example, could implement it differently. That's because the specification allows it.

Sure, ContainsKey isn't thread safe, but my point is that even then, if the dictionary is changed in the middle of the search it will succeed in this specific scenario. [By looking at the code](https://referencesource.microsoft.com/#mscorlib/system/collections/generic/dictionary.cs,bcd13bb775d408f1), I found that it will always stop, and it will never return a false positive, if the dictionary is only being added to... though a false negative is possible, but it does not matter, because, if false is returned, it will be tested again inside the lock.

**Comment by masbicudo** [comment]
Of course, I am unable to analyse all the possibilities to say I was 100% sure ContainsKey would behave correctly... the new implementation, like an immutable object is indeed 100% guaranteed, and I prefer it.

**Comment by ayende** [comment]
@masbicudo ContainsKey may throw, because the Add might create a new array midway, and it isn't doing that safely. 
And mono can't change that behavior, regardless of the spec, because too much will break it if did.

**Comment by masbicudo** [comment]
When I first read about this issue was in an article about ARM processors (I can't find it anymore, it has been years since then), that had a very weak memory model, and another CLR implementation could take advantage of that model to make optimizations, but they stated that it would require the correct use of memory barriers by the developer... since then I have memorized that as a rule: before publishing any object that's used by multiple threads, use a memory barrier.

Maybe it's time to forget that rule... I'm not 100% sure.

**Comment by ayende** [comment]
@masbicudo The CLR impl on the ARM does enforce this, so doesn't matter.
At any rate, note that it doesn't matter, if you publish an instance, and a thread didn't see it, it will go into the lock, and that create its own barrier.
At which point, the second check will find it.

**Comment by masbicudo** [comment]
@ayende The problem is not the dictionary, the problem is the metadata object being half baked.

This is the code inside the lock:

    var meta = GetMemberMetadataNoCache(memberInfo);
    Interlocked.MemoryBarrier();
    cache = new Dictionary<MemberInfo, IJavascriptMemberMetadata>(cache)
    {
        [memberInfo] = meta
    };
    return meta;

If I remove the barrier, a half initialized `meta` could be added to the dictionary, and then assigned to the `cache` variable. If by any chance `cache` becomes visible to another thread before the lock finishes, then a not completely initialized instance of the metadata would be visible.

That's the rule that I'm not sure if I should forget. The rule to protect half baked objects from being exposed.

**Comment by ayende** [comment]
@masbicudo No, that isn't possible at all. You can't see part of the changes to the object in this manner. You are creating a _new_ object here, note modifying an existing one. Once you have a pointer to it, you can be sure that you'll be able to see it in a consistent manner

**Pull request merged**
